sudo: false
language: node_js
branches:
  only:
    - master
matrix:
  fast_finish: true
  include:
    - os: linux
      node_js: '10'
      env: NODE_ENV="test" JOB_PART=test
    - os: linux
      node_js: '12'
      env: NODE_ENV="test" JOB_PART=test
    - os: linux
      node_js: '12'
      env: NODE_ENV="test" JOB_PART=coverage
before_install:
  - 'if [[ `npm -v` != 5* ]]; then npm i -g npm@^6.0.0; fi'
  - nvm --version
  - node --version
  - npm --version
script:
  - 'npm run travis:$JOB_PART'
