sudo: false
language: node_js
branches:
  only:
    - master
matrix:
  fast_finish: true
  include:
    - os: linux
      node_js: '4.3'
      env: WEBPACK_VERSION="2.6.0" JOB_PART=test
    - os: linux
      node_js: '6'
      env: WEBPACK_VERSION="2.6.0" JOB_PART=test
    - os: linux
      node_js: '8'
      env: WEBPACK_VERSION="2.6.0" JOB_PART=coverage
before_install:
  - 'if [[ `npm -v` != 5* ]]; then npm i -g npm@^5.0.0; fi'
  - nvm --version
  - node --version
  - npm --version
script:
  - 'npm run travis:$JOB_PART'
